# Define environment for services using YAML anchors
x-mongodb-env: &mongodb-env
  MONGODB_USER: "${MONGODB_USER:-root}"
  MONGODB_PWD: "${MONGODB_PWD:-dev}"
  MONGODB_DB: "${MONGODB_DB:-scavenger}"
  MONGO_INITDB_ROOT_USERNAME: "${MONGODB_USER:-root}"
  MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_PWD:-dev}"
  MONGO_INITDB_DATABASE: "${MONGODB_DB:-scavenger}"
  MONGODB_ADDR: "${MONGODB_ADDR:-mongodb:27017}"

# ================================================================================
#                       DOCKER SERVICE DEFINITION
# ================================================================================
version: "3.2"
volumes:
  scav-mongodata:
    external: true

networks:
  default:
    external:
      name: scav-devnet

services:
  frontend:
    build:
      context: frontend
    volumes:
      - "./frontend:/app:rw"
    ports:
      - 3000:3000
    depends_on:
      - main
    restart: always

  main:
    build:
      context: backend/main
    restart: always
    depends_on:
      - mongodb
    volumes:
      - "./backend/main:/app:rw"
    ports:
      - 8080:8080
    environment:
      <<: *mongodb-env

  mongodb:
    restart: unless-stopped
    build:
      context: ./db/mongodb/
    environment:
      <<: *mongodb-env
    ports:
      - 27017:27017
    volumes:
      - scav-mongodata:/data/db
